//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBEXBle.Droid {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBEXBle.Droid.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Average과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bank Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BankInformation {
            get {
                return ResourceManager.GetString("BankInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capacity(Ah) :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Capa {
            get {
                return ResourceManager.GetString("Capa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cell Average Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CellAverageData {
            get {
                return ResourceManager.GetString("CellAverageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cell Measurement Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CellMeasurementData {
            get {
                return ResourceManager.GetString("CellMeasurementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CellNumber {
            get {
                return ResourceManager.GetString("CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISCONNECT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisConnect {
            get {
                return ResourceManager.GetString("DisConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOWNLOAD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery Quality Tester Report과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExcelTitle {
            get {
                return ResourceManager.GetString("ExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning (%) :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImpedanceFailAlarm {
            get {
                return ResourceManager.GetString("ImpedanceFailAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Referance (mΩ) :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImpedanceStandardAlarm {
            get {
                return ResourceManager.GetString("ImpedanceStandardAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail (%) :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImpedanceWaringAlarm {
            get {
                return ResourceManager.GetString("ImpedanceWaringAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please install ms-excel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InstallExcel {
            get {
                return ResourceManager.GetString("InstallExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manufacturer :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Maker {
            get {
                return ResourceManager.GetString("Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Volt.(V) :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OverVoltageAlarm {
            get {
                return ResourceManager.GetString("OverVoltageAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measured Place :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Imp.(mΩ)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Resistance {
            get {
                return ResourceManager.GetString("Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Imp.(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResistancePer {
            get {
                return ResourceManager.GetString("ResistancePer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Excel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveExcel {
            get {
                return ResourceManager.GetString("SaveExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXCEL LIST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchExcel {
            get {
                return ResourceManager.GetString("SearchExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONNECT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchIbex {
            get {
                return ResourceManager.GetString("SearchIbex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IBEX DATA과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectData {
            get {
                return ResourceManager.GetString("SelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Site :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp.(℉)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Over Temp.(℉) :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TemperatureAlarm {
            get {
                return ResourceManager.GetString("TemperatureAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ℉과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempSymbol {
            get {
                return ResourceManager.GetString("TempSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min Volt.(V) :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnderVoltageAlarm {
            get {
                return ResourceManager.GetString("UnderVoltageAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volt.(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
    }
}
